export default {
  story: require('../assets/images/story.jpeg'),
  lockIcon: require('../assets/images/lock.png'),
  menuIcon: require('../assets/images/menu.png'),
  saveIcon: require('../assets/images/save.png'),
  heartIcon: require('../assets/images/heart.png'),
  emailIcon: require('../assets/images/email.png'),
  stories: require('../assets/images/stories.jpeg'),
  qrCodeIcon: require('../assets/images/qrCode.png'),
  reportIcon: require('../assets/images/report.png'),
  searchIcon: require('../assets/images/search.png'),
  commentIcon: require('../assets/images/comment.png'),
  messageIcon: require('../assets/images/message.png'),
  profileIcon: require('../assets/images/account.png'),
  informationIcon: require('../assets/images/info.png'),
  phoneIcon: require('../assets/images/smartphone.png'),
  favoriteIcon: require('../assets/images/favorite.png'),
  unfollowIcon: require('../assets/images/unfollow.png'),
  reelActiveIcon: require('../assets/images/reelActive.png'),
  homeActiveIcon: require('../assets/images/homeActive.png'),
  homeInactionIcon: require('../assets/images/homeInactive.png'),
  reelInactiveIcon: require('../assets/images/reelInactive.png'),
};
